env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - dist
rules:
  '@typescript-eslint/indent':
     off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
      singleline:
        delimiter: semi
        requireLast: false
